flowchart TD
%% generated in 0.00s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph Core
        src__opstree__probes__builtin__os_linux__OsKernelProbe__can_probe["can_probe"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe__scan["scan"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe___get_kernel_version["_get_kernel_version"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe___get_arch["_get_arch"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe___get_hostname["_get_hostname"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe___get_uptime["_get_uptime"]
        src__opstree__probes__builtin__os_linux__OsKernelProbe__anomalies["anomalies"]
        src__opstree__probes__builtin__os_linux__OsConfigProbe__can_probe["can_probe"]
        src__opstree__probes__builtin__os_linux__OsConfigProbe__scan["scan"]
        src__opstree__probes__builtin__os_linux__OsConfigProbe___read_config_txt["_read_config_txt"]
        src__opstree__probes__builtin__os_linux__OsConfigProbe___read_cmdline["_read_cmdline"]
        src__opstree__probes__builtin__os_linux__OsConfigProbe__anomalies["anomalies"]
        src__opstree__probes__builtin__service_containers__ServiceContainersProbe__can_probe["can_probe"]
        src__opstree__probes__builtin__service_containers__ServiceContainersProbe__scan["scan"]
        src__opstree__probes__builtin__service_containers__ServiceContainersProbe___list_systemd_services["_list_systemd_services"]
        ...["+112 more"]
    end

    class src__opstree__probes__builtin__os_linux__OsKernelProbe__can_probe,src__opstree__probes__builtin__os_linux__OsKernelProbe__scan,src__opstree__probes__builtin__os_linux__OsKernelProbe___get_kernel_version,src__opstree__probes__builtin__os_linux__OsKernelProbe___get_arch,src__opstree__probes__builtin__os_linux__OsKernelProbe___get_hostname,src__opstree__probes__builtin__os_linux__OsKernelProbe___get_uptime,src__opstree__probes__builtin__os_linux__OsKernelProbe__anomalies,src__opstree__probes__builtin__os_linux__OsConfigProbe__can_probe,src__opstree__probes__builtin__os_linux__OsConfigProbe__scan,src__opstree__probes__builtin__os_linux__OsConfigProbe___read_config_txt entry
