# Generated by `koru --init`; source for non-autonomous shells, or use `koru autonomous up --agent-lane auto` (no source needed).
export KORU_AUTOPILOT_BACKEND='plugin_socket'
export KORU_AUTOPILOT_IDE='jetbrains'
export KORU_AUTOPILOT_INSTANCE='jetbrains'
export KORU_SUGGESTED_QUEUE_ACTOR='koru-jetbrains'
